development:
  adapter: postgresql
  encoding: unicode
  database: donation_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: donation_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: donation_production
  pool: 5
